name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed so the action can push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build

      - name: Disable Jekyll (preserve _next)
        run: touch out/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
          commit-message: "Automated deploy from GitHub Actions"
